AWSTemplateFormatVersion: 2010-09-09
Description: |
  Create static website
#Parameters:
  
Resources:

  WebSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP from the internet # Required
      GroupName: web-sec-group
      SecurityGroupIngress: 
        - CidrIp: "0.0.0.0/0"
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - CidrIp: "0.0.0.0/0"
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22  
      Tags: 
        - Key: Name
          Value: cfn-web-sg


  webserver:
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
        - Key: Name
          Value: Irfan-server
      
      ImageId: ami-053a45fff0a704a47
      InstanceType: t2.micro
      KeyName: irfan-pem
      SecurityGroupIds: 
        - Fn::GetAtt: WebSecGroup.GroupId
      UserData: 
        Fn::Base64:
          |
            #!/bin/bash -x
            yum update -y
            yum install -y httpd
            FOLDER="https://raw.githubusercontent.com/irfanozer/static-website-ec2/refs/heads/main/static-web"
            cd /var/www/html
            wget ${FOLDER}/index.html
            wget ${FOLDER}/cat0.jpg
            wget ${FOLDER}/cat1.jpg
            wget ${FOLDER}/cat2.jpg
            systemctl start httpd
            systemctl enable httpd


Outputs:

  WebsiteURL:
    Description: URL for newly created website
    Value: !Join [ "", [ "http://", Fn::GetAtt: webserver.PublicDnsName ] ]
    
    